# Generated by Django 4.0 on 2022-07-17 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='card',
            name='product',
        ),
        migrations.AddField(
            model_name='card',
            name='product',
            field=models.ManyToManyField(to='main.Product'),
        ),
    ]
