# Generated by Django 4.0 on 2022-07-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_unuathorizeduser_card_unuathorized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='unuathorized',
            new_name='unauthorized',
        ),
    ]
