# Generated by Django 4.0 on 2022-07-17 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_card_user_remove_card_product_card_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='product',
        ),
        migrations.AddField(
            model_name='card',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
    ]
