# Generated by Django 4.0 on 2022-07-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_unuathorized_card_unauthorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='unauthorized',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
