# Generated by Django 4.0 on 2022-07-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_discount_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
