# Generated by Django 4.0.4 on 2022-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_card_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
