# Generated by Django 4.0.4 on 2022-08-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_purchase_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
