# Generated by Django 4.0.4 on 2022-08-28 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_purchase_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='unauthorized',
            field=models.GenericIPAddressField(default="127.0.0.1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='username',
            field=models.CharField(default="127.0.0.1", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
