# Generated by Django 4.0.4 on 2022-08-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_reply_unauthorized_reply_username_alter_reply_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='unauthorized',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
