# Generated by Django 4.0.4 on 2022-08-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_reply_unauthorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
